### ISSUE TITLE
jobs failing due GKE error 401

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-project#124]
As noticed, many jobs are failing due error 401 calling GKE API:
https://bot.staging.kernelci.org/job/kernel-build/77628/console
```
.
PASS
Traceback (most recent call last):
  File "/data/workspace/bot.staging.kernelci.org/k8s-gcp-us-central1/workspace/kernel-build__5/kernelci-core/./config/k8s/wait.py", line 167, in <module>
    main(args)
  File "/data/workspace/bot.staging.kernelci.org/k8s-gcp-us-central1/workspace/kernel-build__5/kernelci-core/./config/k8s/wait.py", line 105, in main
    pod = core.list_namespaced_pod(namespace=args.namespace, watch=False,
  File "/usr/local/lib/python3.9/dist-packages/kubernetes/client/api/core_v1_api.py", line 15697, in list_namespaced_pod
    return self.list_namespaced_pod_with_http_info(namespace, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/dist-packages/kubernetes/client/api/core_v1_api.py", line 15812, in list_namespaced_pod_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/dist-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/dist-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/dist-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.9/dist-packages/kubernetes/client/rest.py", line 240, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.9/dist-packages/kubernetes/client/rest.py", line 234, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Audit-Id': '133dc888-5588-4292-b5d9-f23f4e3dded8', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Fri, 19 Aug 2022 01:21:38 GMT', 'Content-Length': '129'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}

```
Probably we are facing some kind of race condition with tokens or they are getting expired. Maybe we should retry at least once on such error?

**Comment by nuclearcat** [comment]
Issue of relatively short-living GKE access token and mechanism of refreshing it here:
https://github.com/kubernetes-client/python-base/pull/250

**Comment by nuclearcat** [comment]
This weekend kubernetes configs got corrupted by simultaneous GKE refresh:
```
+ kubectl --context aks-kci-us-west3 get nodes
error: error loading config file "/.kube/config": error converting *[]NamedAuthInfo into *map[string]*api.AuthInfo: duplicate name "clusterUser_kernelci_aks-kci-us-east2" in list: [{clusterUser_kernelci_aks-kci-france-central { [45 45 45 45 45 66 69 71 73 78 32 67 69 82 84 73 70 73 67 65 84 69 45 45 45 45 45 10 77 73 73 69 47 68 67 67 65 117 83 103 65 119 73 66 65 103 73 81 102 113 54 74 43 116 69 122 71 114 74 101 77 55 81 53 103 73 74 66 113 68 65 78 66 103 107 113 104 107 105 71 57 119 48 66 65 81 115 70 65 68 65 78 10 77 81 115 119 67 81 89 68 86 81 81 68 69 119 74 106 89 84 65 101 70 119 48 121 77 68 65 49 77 68 89 120 79 68 81 51 78 68 74 97 70 119 48 121 77 106 65 49 77 68 89 120 79 68 85 51 78 68 74 97 77 68 65 120 10 70 122 65 86 66 103 78 86 66 65 111 84 68 110 78 53 99 51 82 108 98 84 112 116 89 88 78 48 90 88 74 122 77 82 85 119 69 119 89 68 86 81 81 68 69 119 120 116 89 88 78 48 90 88 74 106 98 71 108 108 98 110 81 119 10 103 103
```
And all jobs stopped on production and staging

**Comment by aliceinwire** [comment]
> /.kube/config

There is a duplicated name in the /.kube/config ?

**Comment by nuclearcat** [comment]
That's because of race condition i am investigating and proposed solution in PR https://github.com/kernelci/kernelci-jenkins/pull/109. After this PR each job will have its own kubernetes config.
Right now, as GKE tokens are very short-living, way how we run jobs and map configs is not very correct, so likely 2 jobs write .kube/config at same time (and it is same file on jenkins builder host), each with different tokens - and they corrupted it. 
It was already happening a lot that jobs were failing because kubernetes config was containing invalid symbols or it was empty, but now it happened that this corruption was permanent.
